### ISSUE TITLE
Upgrade ruby and sidekiq?

### ISSUE THREAD

**Issue by mperham** [square/shuttle#115]
I noticed Shuttle is using some pretty old dependencies.  Ruby 2.0.0 isn't supported anymore and sidekiq <3 is several years out of date.

**Comment by mperham** [comment]
I got shuttle to build with Ruby 2.2 but 2.3 doesn't appear to work.

**Comment by yunussasmaz** [comment]
Hi @mperham,
Shuttle had been in maintenance mode for a while so we haven't been updating too frequently. But, we are spinning off a new team now, and we are planning on doing a lot of upgrades including Sidekiq, Ruby, Rails, ElasticSearch, all other gems & Postgres->MySql conversion. Upgrading Ruby right away breaks some things, so we will work out those details first.

**Comment by connorshea** [comment]
@yunussasmaz did this happen to go anywhere?

**Comment by robolson** [comment]
Sidekiq has finally been upgraded 😃 . Closing
