### ISSUE TITLE
Keys associated to wrong commits

### ISSUE THREAD

**Issue by hansede** [square/shuttle#58]
I have two Rails projects (project A and project B) that each have the same string in their respective en.yml:

```
conditionsOfUse: Conditions of Use
```

First I upload the HEAD commit from project A to Shuttle, and everything looks fine. Then I upload the HEAD commit from project B, and both instances of 'conditionsOfUse' (one from each project) become associated to the commit from project B. 

The problem can be seen by clicking on the SHA commit ID link for project B. The page that comes up (GET /projects/:project_id/commits/:commit_id), lists 'conditionsOfUse' twice, with different data for each instance. Additionally, 'GET /projects/:project_id/commits/:commit_id/keys.json' lists 'conditionsOfUse' twice. 

There is no association between the 'conditionsOfUse' key from project A and the commit from project B in the commits_keys table in postgres. However, elasticsearch shows the following commit_ids associated to the key from project A:

```
1,2,3,4,5,6,7,8,9,10,11,12,13,14
```

The following line from keys_controller.rb filters on the commit_ids in elasticsearch:

```
query { string "commit_ids:\"#{commit_id}\"" }
```

Hence, the key from project A being associated to project B. The association in elasticsearch of the key in project A to commit_ids 1-14 appears to be incorrect behavior. How this association is formed is a mystery to me.

**Comment by yunussasmaz** [comment]
I have seen and fixed this problem months ago. Closing for now, please re-open if you observe it again.
