### ISSUE TITLE
rake db:migrate db:seed  fails

### ISSUE THREAD

**Issue by taschik** [square/shuttle#61]

**Comment by jamesgmorgan** [comment]
Was it this, if so can you comment on the fix?!

[ERROR] There has been an error when creating the index -- elasticsearch returned:
400 : {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [key_ids] has unsupported parameters:  [as : commits_keys.pluck(:key_id)]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [commit]: Mapping definition for [key_ids] has unsupported parameters:  [as : commits_keys.pluck(:key_id)]","caused_by":{"type":"mapper_parsing_exception","reason":"Mapping definition for [key_ids] has unsupported parameters:  [as : commits_keys.pluck(:key_id)]"}},"status":400}
[ERROR] There has been an error when creating the index -- elasticsearch returned:
400 : {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [index_in_section] has unsupported parameters:  [as : send(:key).index_in_section]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [translation]: Mapping definition for [index_in_section] has unsupported parameters:  [as : send(:key).index_in_section]","caused_by":{"type":"mapper_parsing_exception","reason":"Mapping definition for [index_in_section] has unsupported parameters:  [as : send(:key).index_in_section]"}},"status":400}
